language: cpp
compiler: gcc
dist: xenial
sudo: required
os:
- linux
- osx
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.0-xenial
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt512base qt512websockets
  qt512serialport libgl1-mesa-dev ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt512/bin/qt512-env.sh ;
  fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH"
  ; fi
- qmake Savestate2snes.pro
- make


before_deploy:
- cp icon64x64.png Savestate2snes.app/Contents/MacOs/icone.png
- cp qusb2snesapp.json Savestate2snes.app/Contents/MacOs/
- macdeployqt Savestate2snes.app -dmg


deploy:
  provider: releases
  api_key:
    secure: VSKFSqCNGzYlKes08IrumMV+id5jrsmiKmaQbhcIQ9CvAnIJvJ7OqdkyFIIZbEnIBQGvVdJd+Lx8s0cyRhs10YOPOCObQ/Ikz//qJ4eoX9zL/Xup4yIxseqcYP49y7FOeRONqNWypLfN7L8xvciGfPkPAHP2vWgMzJvZiJJ9QINTGiJrQb/Vn1Vwrgkj4ObvO2PWA5vXy9uyU2jV+0rL5osL1oUt1Zpkxaj8cKsr1S6m0nJd6AGKhoM635hi7iW+KSLyE1k2AC7eMwshvZxjp0iiarkNoPnVcWpGuneSj0o5lZN718NrYPvyQKAlj3P5DG/Oed0u7vlY+vvNdWTuW5He0Rut6yXQoS5JFarJBWjNBfAsk7uBIURsUOKD4lUCmxvxDHHfR+Wo4m3eOEj7GRad/DlpRbtNoILxgRWidYFN/9NBgQfLjg3ph/k7PkIlxNo6NVu/xLWqvIApfpeofBbe15Q0yPOmfhM5nyYvGbhmKxdzch3dyDwx+B3ikCcHvcZVHiUfGtwNljaykP3XI1wphZEbbv038pDkKoNiZc/WWLo+il/827Cs1eyaJ/mck4ER+v7hOCb7ePwXHm5mUQr0R1Xt0/nNc6wzrdGhej6EjaddAoCTUfT/0hTJvqXbv0F9rMRwDOowuKjx7kViaTbcVzf0Vsl0KClYFUYbqHM=
  draft: true
  file: Savestate2snes.dmg
  skip_cleanup: true
  on:
    repo: Skarsnik/Savestate2snes
    tags: true
    condition: $TRAVIS_OS_NAME = osx


