theme: jekyll-theme-cayman
show_downloads: true
github:
    zip_url: https://github.com/Skarsnik/Savestate2snes/releases/download/v0.4.2/savestate2snes-0.4.2.7z
    tar_url: https://github.com/Skarsnik/Savestate2snes/archive/v0.4.2.tar.gz
