theme: jekyll-theme-cayman
show_downloads: true
github:
    zip_url: https://github.com/Skarsnik/Savestate2snes/releases/download/v0.6.1.1/Savestate2Snes-v0.6.1.1.7z
    tar_url: https://github.com/Skarsnik/Savestate2snes/archive/v0.6.1.1.tar.gz
